name: Deploy with Self-Hosted Runner

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  # Gunakan self-hosted runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy application
      run: |
        cd /home/demo/testing/Test
        git pull origin main
        
        echo "Deployment completed!"
