name: Deploy to Local Server

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
          # Buat directory jika belum ada
          mkdir -p /home/demo/app
          cd /home/demo/app
          touch data1.txt
          # Pull changes
          # git pull origin main || git clone https://github.com/${{ github.repository }} .
          
          # Install dependencies (contoh untuk Node.js)
          # npm install
          
          # Build aplikasi
          # npm run build
          
          # Restart service (sesuaikan dengan kebutuhan)
          # sudo systemctl restart your-app-service
        EOF
