name: Deploy with Self-Hosted Runner

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  # Gunakan self-hosted runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm ci
        npm run build

    - name: Deploy application
      run: |
        sudo systemctl restart my-app
        echo "Deployment completed!"
